name: Test and Deploy

on:
  push:
    branch:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{secrets.RENDER_DEPLOY_HOOK}}
